### ISSUE TITLE
Attention map 

### ISSUE THREAD

**Issue by xtzd** [alipay/cvpr2020-plant-pathology#2]
Hi, there！ Thanks for the project! I would like to know the specific method to do the error analysis, which show where the network puts the attention on. like CAM ?

**Comment by nickyi1990** [comment]
> Hi, there！ Thanks for the project! I would like to know the specific method to do the error analysis, which show where the network puts the attention on. like CAM ?

Yes, the picture in error analysis is created by CAM

**Comment by xtzd** [comment]
> > Hi, there！ Thanks for the project! I would like to know the specific method to do the error analysis, which show where the network puts the attention on. like CAM ?
> 
> Yes, the picture in error analysis is created by CAM

Thanks~   : )
