### ISSUE TITLE
About requirements.txt

### ISSUE THREAD

**Issue by xtzd** [alipay/cvpr2020-plant-pathology#3]
Also need Apex? 
Also albumentations and pretrainedmodels packages.

**Comment by fire717** [comment]
Need  albumentations and pretrainedmodels, 
and Apex is optional, you can set precision to 32 to avoid it.

**Comment by nickyi1990** [comment]
> Need albumentations and pretrainedmodels,
> and Apex is optional, you can set precision to 32 to avoid it.

yes,

> Also need Apex?
> Also albumentations and pretrainedmodels packages.

Has been updated!

**Comment by xtzd** [comment]
> > Need albumentations and pretrainedmodels,
> > and Apex is optional, you can set precision to 32 to avoid it.
> 
> yes,
> 
> > Also need Apex?
> > Also albumentations and pretrainedmodels packages.
> 
> Has been updated!

Thank you ~Also, if using pytorch version>1.6, precision 16 is also compatible without installing Apex. But might need some code modification since using newer pytorch-lightning version to support that feature.

**Comment by nickyi1990** [comment]
> > > Need albumentations and pretrainedmodels,
> > > and Apex is optional, you can set precision to 32 to avoid it.
> > 
> > 
> > yes,
> > > Also need Apex?
> > > Also albumentations and pretrainedmodels packages.
> > 
> > 
> > Has been updated!
> 
> Thank you ~Also, if using pytorch version>1.6, precision 16 is also compatible without installing Apex. But might need some code modification since using newer pytorch-lightning version to support that feature.

yes, this is a competition code repo, not a repo that would be update reuglarly, so~ if anyone is using new version pytorch or other lib, they may should change some code :smiley:
