### ISSUE TITLE
『kun』是什么意思，怎么理解。

### ISSUE THREAD

**Issue by snowjade** [alipay/cvpr2020-plant-pathology#8]
![image](https://user-images.githubusercontent.com/11959369/150482947-616d6de7-9aa2-4630-9696-dd51a01a1569.png)
为什么使用这三个字母，是什么意思呢？百思不得其解

**Comment by nickyi1990** [comment]
我的花名~

**Comment by snowjade** [comment]
啧啧 原来是这样
